import type { AnimationPreset } from "@/types";

const ease = {
  linear: "linear",
  easeIn: "cubic-bezier(0.4, 0, 1, 1)",
  easeOut: "cubic-bezier(0, 0, 0.2, 1)",
  easeInOut: "cubic-bezier(0.4, 0, 0.2, 1)",
  bounce: "cubic-bezier(0.34, 1.56, 0.64, 1)",
  spring: "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
  elastic: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
};

export const ANIMATION_PRESETS: AnimationPreset[] = [
  // ENTRANCE ANIMATIONS (50)
  { id: "fade-in", name: "Fade In", category: "Entrance", cssAnimation: "fadeIn", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1", preview: "opacity 0→1" },
  { id: "fade-in-up", name: "Fade In Up", category: "Entrance", cssAnimation: "fadeInUp", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "fade-in-down", name: "Fade In Down", category: "Entrance", cssAnimation: "fadeInDown", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "fade-in-left", name: "Fade In Left", category: "Entrance", cssAnimation: "fadeInLeft", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "fade-in-right", name: "Fade In Right", category: "Entrance", cssAnimation: "fadeInRight", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "slide-from-left", name: "Slide From Left", category: "Entrance", cssAnimation: "slide-from-left", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "slide-from-right", name: "Slide From Right", category: "Entrance", cssAnimation: "slide-from-right", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "slide-from-top", name: "Slide From Top", category: "Entrance", cssAnimation: "slide-from-top", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "slide-from-bottom", name: "Slide From Bottom", category: "Entrance", cssAnimation: "slide-from-bottom", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "zoom-in", name: "Zoom In", category: "Entrance", cssAnimation: "zoom-in", duration: 0.5, easing: ease.bounce, delay: 0, iterationCount: "1" },
  { id: "zoom-out", name: "Zoom Out", category: "Entrance", cssAnimation: "zoom-out", duration: 0.5, easing: ease.bounce, delay: 0, iterationCount: "1" },
  { id: "rotate-in", name: "Rotate In", category: "Entrance", cssAnimation: "rotate-in", duration: 0.7, easing: ease.spring, delay: 0, iterationCount: "1" },
  { id: "bounce-in", name: "Bounce In", category: "Entrance", cssAnimation: "bounce-in", duration: 0.8, easing: ease.bounce, delay: 0, iterationCount: "1" },
  { id: "flip-in-x", name: "Flip In X", category: "Entrance", cssAnimation: "flip-in-x", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "flip-in-y", name: "Flip In Y", category: "Entrance", cssAnimation: "flip-in-y", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "light-speed-in", name: "Light Speed In", category: "Entrance", cssAnimation: "light-speed-in", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "roll-in", name: "Roll In", category: "Entrance", cssAnimation: "rollIn", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "zoom-in-up", name: "Zoom In Up", category: "Entrance", cssAnimation: "zoomInUp", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "zoom-in-down", name: "Zoom In Down", category: "Entrance", cssAnimation: "zoomInDown", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "zoom-in-left", name: "Zoom In Left", category: "Entrance", cssAnimation: "zoomInLeft", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "zoom-in-right", name: "Zoom In Right", category: "Entrance", cssAnimation: "zoomInRight", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "back-in-left", name: "Back In Left", category: "Entrance", cssAnimation: "backInLeft", duration: 0.7, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "back-in-right", name: "Back In Right", category: "Entrance", cssAnimation: "backInRight", duration: 0.7, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "back-in-up", name: "Back In Up", category: "Entrance", cssAnimation: "backInUp", duration: 0.7, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "back-in-down", name: "Back In Down", category: "Entrance", cssAnimation: "backInDown", duration: 0.7, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "drop-in", name: "Drop In", category: "Entrance", cssAnimation: "dropIn", duration: 0.5, easing: ease.bounce, delay: 0, iterationCount: "1" },
  { id: "swing-in", name: "Swing In", category: "Entrance", cssAnimation: "swingIn", duration: 0.7, easing: ease.spring, delay: 0, iterationCount: "1" },
  { id: "spiral-in", name: "Spiral In", category: "Entrance", cssAnimation: "spiralIn", duration: 0.8, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "stretch-in-x", name: "Stretch In X", category: "Entrance", cssAnimation: "stretchInX", duration: 0.5, easing: ease.spring, delay: 0, iterationCount: "1" },
  { id: "stretch-in-y", name: "Stretch In Y", category: "Entrance", cssAnimation: "stretchInY", duration: 0.5, easing: ease.spring, delay: 0, iterationCount: "1" },
  { id: "vanish-in", name: "Vanish In", category: "Entrance", cssAnimation: "vanishIn", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "float-in", name: "Float In", category: "Entrance", cssAnimation: "floatIn", duration: 0.8, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "blur-in", name: "Blur In", category: "Entrance", cssAnimation: "blurIn", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "slit-in-vertical", name: "Slit In Vertical", category: "Entrance", cssAnimation: "slitInVertical", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "slit-in-horizontal", name: "Slit In Horizontal", category: "Entrance", cssAnimation: "slitInHorizontal", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "puff-in", name: "Puff In", category: "Entrance", cssAnimation: "puffIn", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "tilt-in-fwd", name: "Tilt In Forward", category: "Entrance", cssAnimation: "tiltInFwd", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "skew-in-top", name: "Skew In Top", category: "Entrance", cssAnimation: "skewInTop", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "skew-in-bottom", name: "Skew In Bottom", category: "Entrance", cssAnimation: "skewInBottom", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "glitch-in", name: "Glitch In", category: "Entrance", cssAnimation: "glitchIn", duration: 0.4, easing: ease.linear, delay: 0, iterationCount: "1" },
  { id: "wave-in", name: "Wave In", category: "Entrance", cssAnimation: "waveIn", duration: 0.8, easing: ease.easeInOut, delay: 0, iterationCount: "1" },
  { id: "swipe-in-top", name: "Swipe In Top", category: "Entrance", cssAnimation: "swipeInTop", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "swipe-in-bottom", name: "Swipe In Bottom", category: "Entrance", cssAnimation: "swipeInBottom", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "swipe-in-left", name: "Swipe In Left", category: "Entrance", cssAnimation: "swipeInLeft", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "swipe-in-right", name: "Swipe In Right", category: "Entrance", cssAnimation: "swipeInRight", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "door-open", name: "Door Open", category: "Entrance", cssAnimation: "doorOpen", duration: 0.7, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "typewriter", name: "Typewriter", category: "Entrance", cssAnimation: "typewriter", duration: 1.5, easing: "steps(20, end)", delay: 0, iterationCount: "1" },
  { id: "perspective-left", name: "Perspective Left", category: "Entrance", cssAnimation: "perspectiveLeft", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "perspective-right", name: "Perspective Right", category: "Entrance", cssAnimation: "perspectiveRight", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "neon-flicker-in", name: "Neon Flicker In", category: "Entrance", cssAnimation: "neonFlickerIn", duration: 0.8, easing: ease.linear, delay: 0, iterationCount: "1" },
  // ATTENTION SEEKERS (50)
  { id: "pulse", name: "Pulse", category: "Attention", cssAnimation: "pulse-scale", duration: 1, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "bounce", name: "Bounce", category: "Attention", cssAnimation: "bounce", duration: 1, easing: ease.bounce, delay: 0, iterationCount: "infinite" },
  { id: "shake", name: "Shake", category: "Attention", cssAnimation: "shake", duration: 0.6, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "swing", name: "Swing", category: "Attention", cssAnimation: "swing", duration: 1, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "tada", name: "Tada", category: "Attention", cssAnimation: "tada", duration: 1, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "wobble", name: "Wobble", category: "Attention", cssAnimation: "wobble", duration: 1, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "jello", name: "Jello", category: "Attention", cssAnimation: "jello", duration: 0.9, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "rubber-band", name: "Rubber Band", category: "Attention", cssAnimation: "rubber-band", duration: 1, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "heart-beat", name: "Heart Beat", category: "Attention", cssAnimation: "heart-beat", duration: 1.3, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "flash", name: "Flash", category: "Attention", cssAnimation: "flash", duration: 1, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "glow", name: "Glow", category: "Attention", cssAnimation: "glow", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "float", name: "Float", category: "Attention", cssAnimation: "float", duration: 3, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "spin-slow", name: "Spin Slow", category: "Attention", cssAnimation: "spin-slow", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "spin-fast", name: "Spin Fast", category: "Attention", cssAnimation: "spin-fast", duration: 0.5, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "rock", name: "Rock", category: "Attention", cssAnimation: "rock", duration: 0.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "breath", name: "Breath", category: "Attention", cssAnimation: "breath", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "blink", name: "Blink", category: "Attention", cssAnimation: "blink", duration: 1, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "twitch", name: "Twitch", category: "Attention", cssAnimation: "twitch", duration: 0.3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "hover-lift", name: "Hover Lift", category: "Attention", cssAnimation: "hoverLift", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "color-shift", name: "Color Shift", category: "Attention", cssAnimation: "colorShift", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "neon-glow", name: "Neon Glow", category: "Attention", cssAnimation: "neonGlow", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "glitch", name: "Glitch", category: "Attention", cssAnimation: "glitch", duration: 0.8, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "morphing", name: "Morphing", category: "Attention", cssAnimation: "morphing", duration: 4, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "ripple", name: "Ripple", category: "Attention", cssAnimation: "ripple", duration: 1.5, easing: ease.easeOut, delay: 0, iterationCount: "infinite" },
  { id: "radar", name: "Radar", category: "Attention", cssAnimation: "radar", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "tilt", name: "Tilt", category: "Attention", cssAnimation: "tilt", duration: 3, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "vibrate", name: "Vibrate", category: "Attention", cssAnimation: "vibrate", duration: 0.1, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "squeeze-x", name: "Squeeze X", category: "Attention", cssAnimation: "squeezeX", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "squeeze-y", name: "Squeeze Y", category: "Attention", cssAnimation: "squeezeY", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "orbit", name: "Orbit", category: "Attention", cssAnimation: "orbit", duration: 4, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "pendulum", name: "Pendulum", category: "Attention", cssAnimation: "pendulum", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "figure-8", name: "Figure 8", category: "Attention", cssAnimation: "figure8", duration: 4, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "wave", name: "Wave", category: "Attention", cssAnimation: "wave", duration: 0.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "snappy", name: "Snappy", category: "Attention", cssAnimation: "snappy", duration: 0.4, easing: ease.spring, delay: 0, iterationCount: "infinite" },
  { id: "fire", name: "Fire", category: "Attention", cssAnimation: "fire", duration: 0.6, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "electric", name: "Electric", category: "Attention", cssAnimation: "electric", duration: 0.2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "shiver", name: "Shiver", category: "Attention", cssAnimation: "shiver", duration: 0.15, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "bounce-x", name: "Bounce X", category: "Attention", cssAnimation: "bounceX", duration: 1, easing: ease.bounce, delay: 0, iterationCount: "infinite" },
  { id: "bounce-y", name: "Bounce Y", category: "Attention", cssAnimation: "bounceY", duration: 1, easing: ease.bounce, delay: 0, iterationCount: "infinite" },
  { id: "zoom-pulse", name: "Zoom Pulse", category: "Attention", cssAnimation: "zoomPulse", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "attention-seeker-1", name: "Spotlight", category: "Attention", cssAnimation: "spotlight", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "shadow-pulse", name: "Shadow Pulse", category: "Attention", cssAnimation: "shadowPulse", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "stretch-x", name: "Stretch X", category: "Attention", cssAnimation: "stretchX", duration: 1.5, easing: ease.spring, delay: 0, iterationCount: "infinite" },
  { id: "flip-h", name: "Flip H", category: "Attention", cssAnimation: "flipH", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "flip-v", name: "Flip V", category: "Attention", cssAnimation: "flipV", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "bounce-rotate", name: "Bounce Rotate", category: "Attention", cssAnimation: "bounceRotate", duration: 1.5, easing: ease.bounce, delay: 0, iterationCount: "infinite" },
  { id: "sway", name: "Sway", category: "Attention", cssAnimation: "sway", duration: 4, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "sink", name: "Sink", category: "Attention", cssAnimation: "sink", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "glisten", name: "Glisten", category: "Attention", cssAnimation: "glisten", duration: 2.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "wobble-bottom", name: "Wobble Bottom", category: "Attention", cssAnimation: "wobbleBottom", duration: 1, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "nod", name: "Nod", category: "Attention", cssAnimation: "nod", duration: 1, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  // EXIT ANIMATIONS (50)
  { id: "fade-out", name: "Fade Out", category: "Exit", cssAnimation: "fadeOut", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "fade-out-up", name: "Fade Out Up", category: "Exit", cssAnimation: "fadeOutUp", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "fade-out-down", name: "Fade Out Down", category: "Exit", cssAnimation: "fadeOutDown", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "fade-out-left", name: "Fade Out Left", category: "Exit", cssAnimation: "fadeOutLeft", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "fade-out-right", name: "Fade Out Right", category: "Exit", cssAnimation: "fadeOutRight", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "zoom-out-exit", name: "Zoom Out", category: "Exit", cssAnimation: "zoomOut", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "slide-out-left", name: "Slide Out Left", category: "Exit", cssAnimation: "slideOutLeft", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "slide-out-right", name: "Slide Out Right", category: "Exit", cssAnimation: "slideOutRight", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "slide-out-up", name: "Slide Out Up", category: "Exit", cssAnimation: "slideOutUp", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "slide-out-down", name: "Slide Out Down", category: "Exit", cssAnimation: "slideOutDown", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "flip-out-x", name: "Flip Out X", category: "Exit", cssAnimation: "flipOutX", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "flip-out-y", name: "Flip Out Y", category: "Exit", cssAnimation: "flipOutY", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "rotate-out", name: "Rotate Out", category: "Exit", cssAnimation: "rotateOut", duration: 0.7, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "roll-out", name: "Roll Out", category: "Exit", cssAnimation: "rollOut", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "puff-out", name: "Puff Out", category: "Exit", cssAnimation: "puffOut", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "vanish-out", name: "Vanish Out", category: "Exit", cssAnimation: "vanishOut", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "blur-out", name: "Blur Out", category: "Exit", cssAnimation: "blurOut", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "shrink-out", name: "Shrink Out", category: "Exit", cssAnimation: "shrinkOut", duration: 0.4, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "shatter", name: "Shatter", category: "Exit", cssAnimation: "shatter", duration: 0.8, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "implode", name: "Implode", category: "Exit", cssAnimation: "implode", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "drain", name: "Drain", category: "Exit", cssAnimation: "drain", duration: 0.8, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "fold-out", name: "Fold Out", category: "Exit", cssAnimation: "foldOut", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "back-out-left", name: "Back Out Left", category: "Exit", cssAnimation: "backOutLeft", duration: 0.7, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "back-out-right", name: "Back Out Right", category: "Exit", cssAnimation: "backOutRight", duration: 0.7, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "back-out-up", name: "Back Out Up", category: "Exit", cssAnimation: "backOutUp", duration: 0.7, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "back-out-down", name: "Back Out Down", category: "Exit", cssAnimation: "backOutDown", duration: 0.7, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "hinge", name: "Hinge", category: "Exit", cssAnimation: "hinge", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "1" },
  { id: "jack-out", name: "Jack In Box Out", category: "Exit", cssAnimation: "jackOut", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "dive-out", name: "Dive Out", category: "Exit", cssAnimation: "diveOut", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "swirl-out", name: "Swirl Out", category: "Exit", cssAnimation: "swirlOut", duration: 0.7, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "curl-out", name: "Curl Out", category: "Exit", cssAnimation: "curlOut", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "evaporate", name: "Evaporate", category: "Exit", cssAnimation: "evaporate", duration: 0.8, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "drop-out", name: "Drop Out", category: "Exit", cssAnimation: "dropOut", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "sink-out", name: "Sink Out", category: "Exit", cssAnimation: "sinkOut", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "fly-out-left", name: "Fly Out Left", category: "Exit", cssAnimation: "flyOutLeft", duration: 0.4, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "fly-out-right", name: "Fly Out Right", category: "Exit", cssAnimation: "flyOutRight", duration: 0.4, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "skew-out", name: "Skew Out", category: "Exit", cssAnimation: "skewOut", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "tilt-out", name: "Tilt Out", category: "Exit", cssAnimation: "tiltOut", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "spiral-out", name: "Spiral Out", category: "Exit", cssAnimation: "spiralOut", duration: 0.8, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "stretch-out-x", name: "Stretch Out X", category: "Exit", cssAnimation: "stretchOutX", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "stretch-out-y", name: "Stretch Out Y", category: "Exit", cssAnimation: "stretchOutY", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "rubber-out", name: "Rubber Out", category: "Exit", cssAnimation: "rubberOut", duration: 0.7, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "crack-out", name: "Crack Out", category: "Exit", cssAnimation: "crackOut", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "pixel-dissolve", name: "Pixel Dissolve", category: "Exit", cssAnimation: "pixelDissolve", duration: 0.8, easing: ease.linear, delay: 0, iterationCount: "1" },
  { id: "compress-out", name: "Compress Out", category: "Exit", cssAnimation: "compressOut", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "wipe-out-left", name: "Wipe Out Left", category: "Exit", cssAnimation: "wipeOutLeft", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "wipe-out-right", name: "Wipe Out Right", category: "Exit", cssAnimation: "wipeOutRight", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "wipe-out-up", name: "Wipe Out Up", category: "Exit", cssAnimation: "wipeOutUp", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "wipe-out-down", name: "Wipe Out Down", category: "Exit", cssAnimation: "wipeOutDown", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "glitch-out", name: "Glitch Out", category: "Exit", cssAnimation: "glitchOut", duration: 0.4, easing: ease.linear, delay: 0, iterationCount: "1" },
  { id: "neon-off", name: "Neon Off", category: "Exit", cssAnimation: "neonOff", duration: 0.5, easing: ease.linear, delay: 0, iterationCount: "1" },
  // SPECIAL / CREATIVE (60)
  { id: "typewriter-loop", name: "Typewriter Loop", category: "Special", cssAnimation: "typewriterLoop", duration: 3, easing: "steps(20,end)", delay: 0, iterationCount: "infinite" },
  { id: "counter-spin", name: "Counter Spin", category: "Special", cssAnimation: "counterSpin", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "morph-path", name: "Morph Path", category: "Special", cssAnimation: "morphPath", duration: 3, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "liquid", name: "Liquid", category: "Special", cssAnimation: "liquid", duration: 4, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "particle-burst", name: "Particle Burst", category: "Special", cssAnimation: "particleBurst", duration: 1, easing: ease.easeOut, delay: 0, iterationCount: "infinite" },
  { id: "matrix", name: "Matrix Fall", category: "Special", cssAnimation: "matrixFall", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "warp", name: "Warp", category: "Special", cssAnimation: "warp", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "fire-effect", name: "Fire Effect", category: "Special", cssAnimation: "fireEffect", duration: 0.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "water-wave", name: "Water Wave", category: "Special", cssAnimation: "waterWave", duration: 3, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "smoke", name: "Smoke Rise", category: "Special", cssAnimation: "smokeRise", duration: 3, easing: ease.easeOut, delay: 0, iterationCount: "infinite" },
  { id: "loading-spin", name: "Loading Spin", category: "Special", cssAnimation: "loadingSpin", duration: 1, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "clock", name: "Clock Tick", category: "Special", cssAnimation: "clockTick", duration: 1, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "dna-helix", name: "DNA Helix", category: "Special", cssAnimation: "dnaHelix", duration: 3, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "rubik", name: "Rubik Rotate", category: "Special", cssAnimation: "rubikRotate", duration: 4, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "bounce-chain", name: "Bounce Chain", category: "Special", cssAnimation: "bounceChain", duration: 1.5, easing: ease.bounce, delay: 0, iterationCount: "infinite" },
  { id: "cascading", name: "Cascading", category: "Special", cssAnimation: "cascading", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "magnetic", name: "Magnetic", category: "Special", cssAnimation: "magnetic", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "gravity", name: "Gravity Fall", category: "Special", cssAnimation: "gravityFall", duration: 1, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "splat", name: "Splat", category: "Special", cssAnimation: "splat", duration: 0.5, easing: ease.bounce, delay: 0, iterationCount: "1" },
  { id: "confetti", name: "Confetti", category: "Special", cssAnimation: "confetti", duration: 2, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "explode", name: "Explode", category: "Special", cssAnimation: "explode", duration: 0.8, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "star-burst", name: "Star Burst", category: "Special", cssAnimation: "starBurst", duration: 0.8, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-wave", name: "Text Wave", category: "Special", cssAnimation: "textWave", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "gradient-shift", name: "Gradient Shift", category: "Special", cssAnimation: "gradientShift", duration: 4, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "rainbow", name: "Rainbow", category: "Special", cssAnimation: "rainbow", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "shimmer-effect", name: "Shimmer Effect", category: "Special", cssAnimation: "shimmerEffect", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "mirror", name: "Mirror Flip", category: "Special", cssAnimation: "mirrorFlip", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "kaleidoscope", name: "Kaleidoscope", category: "Special", cssAnimation: "kaleidoscope", duration: 5, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "cartoon", name: "Cartoon Pop", category: "Special", cssAnimation: "cartoonPop", duration: 0.5, easing: ease.spring, delay: 0, iterationCount: "infinite" },
  { id: "comic-shake", name: "Comic Shake", category: "Special", cssAnimation: "comicShake", duration: 0.3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "retro-flicker", name: "Retro Flicker", category: "Special", cssAnimation: "retroFlicker", duration: 0.15, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "vhs-glitch", name: "VHS Glitch", category: "Special", cssAnimation: "vhsGlitch", duration: 0.5, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "scan-line", name: "Scan Line", category: "Special", cssAnimation: "scanLine", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "hologram", name: "Hologram", category: "Special", cssAnimation: "hologram", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "portal", name: "Portal Open", category: "Special", cssAnimation: "portalOpen", duration: 1, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "supernova", name: "Supernova", category: "Special", cssAnimation: "supernova", duration: 1.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "crystallize", name: "Crystallize", category: "Special", cssAnimation: "crystallize", duration: 1, easing: ease.spring, delay: 0, iterationCount: "1" },
  { id: "firework", name: "Firework", category: "Special", cssAnimation: "firework", duration: 1.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "ink-drop", name: "Ink Drop", category: "Special", cssAnimation: "inkDrop", duration: 1.2, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "paint-reveal", name: "Paint Reveal", category: "Special", cssAnimation: "paintReveal", duration: 1, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "pixel-in", name: "Pixel In", category: "Special", cssAnimation: "pixelIn", duration: 0.8, easing: ease.linear, delay: 0, iterationCount: "1" },
  { id: "neon-build", name: "Neon Build", category: "Special", cssAnimation: "neonBuild", duration: 1.5, easing: ease.linear, delay: 0, iterationCount: "1" },
  { id: "matrix-in", name: "Matrix In", category: "Special", cssAnimation: "matrixIn", duration: 2, easing: ease.linear, delay: 0, iterationCount: "1" },
  { id: "dissolve-in", name: "Dissolve In", category: "Special", cssAnimation: "dissolveIn", duration: 1, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "crystallize-in", name: "Crystallize In", category: "Special", cssAnimation: "crystallizeIn", duration: 1, easing: ease.spring, delay: 0, iterationCount: "1" },
  { id: "tornado", name: "Tornado", category: "Special", cssAnimation: "tornado", duration: 0.8, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "ice-freeze", name: "Ice Freeze", category: "Special", cssAnimation: "iceFreeze", duration: 1.2, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "lightning", name: "Lightning", category: "Special", cssAnimation: "lightning", duration: 0.5, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "magnetic-pull", name: "Magnetic Pull", category: "Special", cssAnimation: "magneticPull", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "stagger-in", name: "Stagger In", category: "Special", cssAnimation: "staggerIn", duration: 1.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  // TEXT ANIMATIONS (50)
  { id: "text-blur-in", name: "Blur In", category: "Text", cssAnimation: "textBlurIn", duration: 0.8, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-slide-up", name: "Slide Up", category: "Text", cssAnimation: "textSlideUp", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-slide-down", name: "Slide Down", category: "Text", cssAnimation: "textSlideDown", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-scale", name: "Scale Up", category: "Text", cssAnimation: "textScale", duration: 0.5, easing: ease.bounce, delay: 0, iterationCount: "1" },
  { id: "text-color-wave", name: "Color Wave", category: "Text", cssAnimation: "textColorWave", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "text-shimmer", name: "Shimmer", category: "Text", cssAnimation: "textShimmer", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "text-neon", name: "Neon Glow", category: "Text", cssAnimation: "textNeon", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "text-glitch", name: "Glitch", category: "Text", cssAnimation: "textGlitch", duration: 0.8, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "text-rainbow", name: "Rainbow", category: "Text", cssAnimation: "textRainbow", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "text-flicker", name: "Flicker", category: "Text", cssAnimation: "textFlicker", duration: 1, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "text-bounce-letters", name: "Bounce Letters", category: "Text", cssAnimation: "textBounceLetters", duration: 1, easing: ease.bounce, delay: 0, iterationCount: "infinite" },
  { id: "text-wave-letters", name: "Wave Letters", category: "Text", cssAnimation: "textWaveLetters", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "text-fade-words", name: "Fade Words", category: "Text", cssAnimation: "textFadeWords", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "text-reveal-clip", name: "Clip Reveal", category: "Text", cssAnimation: "textRevealClip", duration: 1, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-push-up", name: "Push Up", category: "Text", cssAnimation: "textPushUp", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-push-down", name: "Push Down", category: "Text", cssAnimation: "textPushDown", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-focus-in", name: "Focus In", category: "Text", cssAnimation: "textFocusIn", duration: 0.8, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-shadow-drop", name: "Shadow Drop", category: "Text", cssAnimation: "textShadowDrop", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-letter-spacing", name: "Letter Spacing", category: "Text", cssAnimation: "textLetterSpacing", duration: 0.8, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-split-reveal", name: "Split Reveal", category: "Text", cssAnimation: "textSplitReveal", duration: 1, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-stamp", name: "Stamp", category: "Text", cssAnimation: "textStamp", duration: 0.3, easing: ease.spring, delay: 0, iterationCount: "1" },
  { id: "text-swipe-in", name: "Swipe In", category: "Text", cssAnimation: "textSwipeIn", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-rotate-words", name: "Rotate Words", category: "Text", cssAnimation: "textRotateWords", duration: 3, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "text-scramble", name: "Scramble", category: "Text", cssAnimation: "textScramble", duration: 1.5, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "text-underline-grow", name: "Underline Grow", category: "Text", cssAnimation: "textUnderlineGrow", duration: 0.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-highlight", name: "Highlight Sweep", category: "Text", cssAnimation: "textHighlight", duration: 0.8, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-gradient-fill", name: "Gradient Fill", category: "Text", cssAnimation: "textGradientFill", duration: 1, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "text-3d-flip", name: "3D Flip", category: "Text", cssAnimation: "text3dFlip", duration: 0.8, easing: ease.easeInOut, delay: 0, iterationCount: "1" },
  { id: "text-pop", name: "Pop", category: "Text", cssAnimation: "textPop", duration: 0.4, easing: ease.spring, delay: 0, iterationCount: "1" },
  { id: "text-retract-up", name: "Retract Up", category: "Text", cssAnimation: "textRetractUp", duration: 0.5, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  // TRANSFORM / MOTION (50)
  { id: "slide-left-loop", name: "Slide Left Loop", category: "Motion", cssAnimation: "slideLeftLoop", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "slide-right-loop", name: "Slide Right Loop", category: "Motion", cssAnimation: "slideRightLoop", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "slide-up-loop", name: "Slide Up Loop", category: "Motion", cssAnimation: "slideUpLoop", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "slide-down-loop", name: "Slide Down Loop", category: "Motion", cssAnimation: "slideDownLoop", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "path-circle", name: "Circle Path", category: "Motion", cssAnimation: "pathCircle", duration: 4, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "path-figure8", name: "Figure-8 Path", category: "Motion", cssAnimation: "pathFigure8", duration: 6, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "path-zigzag", name: "Zigzag Path", category: "Motion", cssAnimation: "pathZigzag", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "path-spiral", name: "Spiral Path", category: "Motion", cssAnimation: "pathSpiral", duration: 4, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "path-bounce-floor", name: "Bounce Floor", category: "Motion", cssAnimation: "pathBounceFloor", duration: 1.5, easing: ease.bounce, delay: 0, iterationCount: "infinite" },
  { id: "path-pendulum-arc", name: "Pendulum Arc", category: "Motion", cssAnimation: "pathPendulumArc", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "rotate-x", name: "Rotate X", category: "Motion", cssAnimation: "rotateX", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "rotate-y", name: "Rotate Y", category: "Motion", cssAnimation: "rotateY", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "rotate-z", name: "Rotate Z", category: "Motion", cssAnimation: "rotateZ", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "rotate-cw", name: "Rotate CW", category: "Motion", cssAnimation: "rotateCW", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "rotate-ccw", name: "Rotate CCW", category: "Motion", cssAnimation: "rotateCCW", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "grow-shrink", name: "Grow & Shrink", category: "Motion", cssAnimation: "growShrink", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "expand-contract", name: "Expand & Contract", category: "Motion", cssAnimation: "expandContract", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "skew-left", name: "Skew Left", category: "Motion", cssAnimation: "skewLeft", duration: 1, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "skew-right", name: "Skew Right", category: "Motion", cssAnimation: "skewRight", duration: 1, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "spring-x", name: "Spring X", category: "Motion", cssAnimation: "springX", duration: 1.5, easing: ease.spring, delay: 0, iterationCount: "infinite" },
  { id: "spring-y", name: "Spring Y", category: "Motion", cssAnimation: "springY", duration: 1.5, easing: ease.spring, delay: 0, iterationCount: "infinite" },
  { id: "snap-in", name: "Snap In", category: "Motion", cssAnimation: "snapIn", duration: 0.3, easing: ease.spring, delay: 0, iterationCount: "1" },
  { id: "elastic-in", name: "Elastic In", category: "Motion", cssAnimation: "elasticIn", duration: 1, easing: ease.spring, delay: 0, iterationCount: "1" },
  { id: "elastic-out", name: "Elastic Out", category: "Motion", cssAnimation: "elasticOut", duration: 1, easing: ease.spring, delay: 0, iterationCount: "1" },
  { id: "loop-rotate-360", name: "Loop 360", category: "Motion", cssAnimation: "loop360", duration: 1, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "swing-360", name: "Swing 360", category: "Motion", cssAnimation: "swing360", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "yo-yo-scale", name: "Yo-Yo Scale", category: "Motion", cssAnimation: "yoyoScale", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "seesaw", name: "Seesaw", category: "Motion", cssAnimation: "seesaw", duration: 2, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "drift-left", name: "Drift Left", category: "Motion", cssAnimation: "driftLeft", duration: 5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "drift-right", name: "Drift Right", category: "Motion", cssAnimation: "driftRight", duration: 5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "track-left", name: "Track Left", category: "Motion", cssAnimation: "trackLeft", duration: 4, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "track-right", name: "Track Right", category: "Motion", cssAnimation: "trackRight", duration: 4, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "fly-in-circle", name: "Fly In Circle", category: "Motion", cssAnimation: "flyInCircle", duration: 3, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "momentum-left", name: "Momentum Left", category: "Motion", cssAnimation: "momentumLeft", duration: 2, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "momentum-right", name: "Momentum Right", category: "Motion", cssAnimation: "momentumRight", duration: 2, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "arc-left", name: "Arc Left", category: "Motion", cssAnimation: "arcLeft", duration: 1.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "arc-right", name: "Arc Right", category: "Motion", cssAnimation: "arcRight", duration: 1.5, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "swoosh-in", name: "Swoosh In", category: "Motion", cssAnimation: "swooshIn", duration: 0.6, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "swoosh-out", name: "Swoosh Out", category: "Motion", cssAnimation: "swooshOut", duration: 0.6, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "ricochet", name: "Ricochet", category: "Motion", cssAnimation: "ricochet", duration: 1.5, easing: ease.bounce, delay: 0, iterationCount: "1" },
  { id: "catapult", name: "Catapult", category: "Motion", cssAnimation: "catapult", duration: 1, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "parabola-up", name: "Parabola Up", category: "Motion", cssAnimation: "parabolaUp", duration: 1.2, easing: ease.easeOut, delay: 0, iterationCount: "1" },
  { id: "parabola-down", name: "Parabola Down", category: "Motion", cssAnimation: "parabolaDown", duration: 1.2, easing: ease.easeIn, delay: 0, iterationCount: "1" },
  { id: "pinball", name: "Pinball", category: "Motion", cssAnimation: "pinball", duration: 2, easing: ease.bounce, delay: 0, iterationCount: "infinite" },
  { id: "march-left", name: "March Left", category: "Motion", cssAnimation: "marchLeft", duration: 0.5, easing: "steps(4)", delay: 0, iterationCount: "infinite" },
  { id: "march-right", name: "March Right", category: "Motion", cssAnimation: "marchRight", duration: 0.5, easing: "steps(4)", delay: 0, iterationCount: "infinite" },
  { id: "page-turn", name: "Page Turn", category: "Motion", cssAnimation: "pageTurn", duration: 1, easing: ease.easeInOut, delay: 0, iterationCount: "1" },
  { id: "rolling-ball", name: "Rolling Ball", category: "Motion", cssAnimation: "rollingBall", duration: 2, easing: ease.linear, delay: 0, iterationCount: "infinite" },
  { id: "tipping", name: "Tipping", category: "Motion", cssAnimation: "tipping", duration: 1.5, easing: ease.easeInOut, delay: 0, iterationCount: "infinite" },
  { id: "yoyo", name: "Yo-Yo", category: "Motion", cssAnimation: "yoyo", duration: 1, easing: ease.bounce, delay: 0, iterationCount: "infinite" },
];

export const ANIMATION_CATEGORIES = ["All", ...Array.from(new Set(ANIMATION_PRESETS.map(p => p.category)))];

export function getAnimationCSS(preset: AnimationPreset): string {
  return `animation: ${preset.cssAnimation} ${preset.duration}s ${preset.easing} ${preset.delay}s ${preset.iterationCount};`;
}
