export const ICON_LIBRARY = [
  { id: "star", name: "Star", content: "★", category: "Shapes" },
  { id: "heart", name: "Heart", content: "♥", category: "Shapes" },
  { id: "diamond", name: "Diamond", content: "◆", category: "Shapes" },
  { id: "circle", name: "Circle", content: "●", category: "Shapes" },
  { id: "triangle-up", name: "Triangle Up", content: "▲", category: "Shapes" },
  { id: "triangle-down", name: "Triangle Down", content: "▼", category: "Shapes" },
  { id: "pentagon", name: "Pentagon", content: "⬠", category: "Shapes" },
  { id: "hexagon", name: "Hexagon", content: "⬡", category: "Shapes" },
  { id: "arrow-right", name: "Arrow Right", content: "→", category: "Arrows" },
  { id: "arrow-left", name: "Arrow Left", content: "←", category: "Arrows" },
  { id: "arrow-up", name: "Arrow Up", content: "↑", category: "Arrows" },
  { id: "arrow-down", name: "Arrow Down", content: "↓", category: "Arrows" },
  { id: "double-arrow-right", name: "Double Arrow Right", content: "»", category: "Arrows" },
  { id: "double-arrow-left", name: "Double Arrow Left", content: "«", category: "Arrows" },
  { id: "checkmark", name: "Checkmark", content: "✓", category: "UI" },
  { id: "cross", name: "Cross", content: "✗", category: "UI" },
  { id: "plus", name: "Plus", content: "+", category: "UI" },
  { id: "minus", name: "Minus", content: "−", category: "UI" },
  { id: "info", name: "Info", content: "ℹ", category: "UI" },
  { id: "warning", name: "Warning", content: "⚠", category: "UI" },
  { id: "play", name: "Play", content: "▶", category: "Media" },
  { id: "pause", name: "Pause", content: "⏸", category: "Media" },
  { id: "stop", name: "Stop", content: "⏹", category: "Media" },
  { id: "skip-forward", name: "Skip Forward", content: "⏭", category: "Media" },
  { id: "skip-back", name: "Skip Back", content: "⏮", category: "Media" },
  { id: "volume", name: "Volume", content: "🔊", category: "Media" },
  { id: "mute", name: "Mute", content: "🔇", category: "Media" },
  { id: "lightning", name: "Lightning", content: "⚡", category: "Nature" },
  { id: "fire", name: "Fire", content: "🔥", category: "Nature" },
  { id: "snowflake", name: "Snowflake", content: "❄", category: "Nature" },
  { id: "sun", name: "Sun", content: "☀", category: "Nature" },
  { id: "moon", name: "Moon", content: "☽", category: "Nature" },
  { id: "cloud", name: "Cloud", content: "☁", category: "Nature" },
  { id: "infinity", name: "Infinity", content: "∞", category: "Math" },
  { id: "sigma", name: "Sigma", content: "Σ", category: "Math" },
  { id: "pi", name: "Pi", content: "π", category: "Math" },
  { id: "copyright", name: "Copyright", content: "©", category: "Legal" },
  { id: "trademark", name: "Trademark", content: "™", category: "Legal" },
  { id: "registered", name: "Registered", content: "®", category: "Legal" },
  { id: "music-note", name: "Music Note", content: "♪", category: "Music" },
  { id: "music-notes", name: "Music Notes", content: "♫", category: "Music" },
  { id: "clef", name: "Treble Clef", content: "𝄞", category: "Music" },
  { id: "lock", name: "Lock", content: "🔒", category: "Security" },
  { id: "unlock", name: "Unlock", content: "🔓", category: "Security" },
  { id: "key", name: "Key", content: "🔑", category: "Security" },
  { id: "shield", name: "Shield", content: "🛡", category: "Security" },
  { id: "globe", name: "Globe", content: "🌐", category: "Web" },
  { id: "link", name: "Link", content: "🔗", category: "Web" },
  { id: "code-brackets", name: "Code", content: "{ }", category: "Dev" },
  { id: "hash", name: "Hash", content: "#", category: "Dev" },
  { id: "at", name: "At Sign", content: "@", category: "Dev" },
  { id: "crown", name: "Crown", content: "♛", category: "Shapes" },
  { id: "flower", name: "Flower", content: "✿", category: "Nature" },
  { id: "leaf", name: "Leaf", content: "🍃", category: "Nature" },
  { id: "wave", name: "Wave", content: "〰", category: "Shapes" },
  { id: "sparkle", name: "Sparkle", content: "✨", category: "Special" },
  { id: "ribbon", name: "Ribbon", content: "🎀", category: "Special" },
  { id: "trophy", name: "Trophy", content: "🏆", category: "Special" },
  { id: "medal", name: "Medal", content: "🎖", category: "Special" },
  { id: "gem", name: "Gem", content: "💎", category: "Special" },
  { id: "rocket", name: "Rocket", content: "🚀", category: "Special" },
];

export const OBJECTS_3D = [
  { id: "cube", name: "Cube", category: "Geometric", thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=80&h=80&fit=crop", tags: ["basic", "3d"] },
  { id: "sphere", name: "Sphere", category: "Geometric", thumbnail: "https://images.unsplash.com/photo-1617791160536-598cf32026fb?w=80&h=80&fit=crop", tags: ["basic", "3d"] },
  { id: "torus", name: "Torus", category: "Geometric", thumbnail: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=80&h=80&fit=crop", tags: ["basic", "3d"] },
  { id: "cylinder", name: "Cylinder", category: "Geometric", thumbnail: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=80&h=80&fit=crop", tags: ["basic", "3d"] },
  { id: "cone", name: "Cone", category: "Geometric", thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=80&h=80&fit=crop", tags: ["basic", "3d"] },
  { id: "diamond-3d", name: "Diamond", category: "Geometric", thumbnail: "https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=80&h=80&fit=crop", tags: ["gem", "3d"] },
  { id: "pyramid", name: "Pyramid", category: "Geometric", thumbnail: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=80&h=80&fit=crop", tags: ["basic", "3d"] },
  { id: "octahedron", name: "Octahedron", category: "Geometric", thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=80&h=80&fit=crop", tags: ["geometric", "3d"] },
  { id: "robot", name: "Robot", category: "Characters", thumbnail: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=80&h=80&fit=crop", tags: ["character", "tech"] },
  { id: "astronaut", name: "Astronaut", category: "Characters", thumbnail: "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=80&h=80&fit=crop", tags: ["character", "space"] },
  { id: "laptop", name: "Laptop", category: "Technology", thumbnail: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=80&h=80&fit=crop", tags: ["tech", "device"] },
  { id: "phone", name: "Phone", category: "Technology", thumbnail: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=80&h=80&fit=crop", tags: ["tech", "device"] },
  { id: "tablet", name: "Tablet", category: "Technology", thumbnail: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=80&h=80&fit=crop", tags: ["tech", "device"] },
  { id: "headphones", name: "Headphones", category: "Technology", thumbnail: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=80&h=80&fit=crop", tags: ["tech", "audio"] },
  { id: "camera", name: "Camera", category: "Technology", thumbnail: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=80&h=80&fit=crop", tags: ["tech", "photo"] },
  { id: "trophy-3d", name: "Trophy", category: "Objects", thumbnail: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=80&h=80&fit=crop", tags: ["award", "object"] },
  { id: "crown-3d", name: "Crown", category: "Objects", thumbnail: "https://images.unsplash.com/photo-1598128558393-70ff21433be0?w=80&h=80&fit=crop", tags: ["award", "object"] },
  { id: "crystal-ball", name: "Crystal Ball", category: "Objects", thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=80&h=80&fit=crop", tags: ["magic", "sphere"] },
  { id: "shield-3d", name: "Shield", category: "Objects", thumbnail: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=80&h=80&fit=crop", tags: ["security", "object"] },
  { id: "rocket-3d", name: "Rocket", category: "Space", thumbnail: "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=80&h=80&fit=crop", tags: ["space", "tech"] },
  { id: "planet", name: "Planet", category: "Space", thumbnail: "https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=80&h=80&fit=crop", tags: ["space", "sphere"] },
  { id: "satellite", name: "Satellite", category: "Space", thumbnail: "https://images.unsplash.com/photo-1541873676-a18131494184?w=80&h=80&fit=crop", tags: ["space", "tech"] },
  { id: "star-3d", name: "Star", category: "Space", thumbnail: "https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=80&h=80&fit=crop", tags: ["space", "decoration"] },
  { id: "arrow-3d", name: "3D Arrow", category: "UI Elements", thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=80&h=80&fit=crop", tags: ["ui", "direction"] },
  { id: "button-3d", name: "3D Button", category: "UI Elements", thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=80&h=80&fit=crop", tags: ["ui", "button"] },
  { id: "toggle-3d", name: "3D Toggle", category: "UI Elements", thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=80&h=80&fit=crop", tags: ["ui", "control"] },
  { id: "loader-3d", name: "3D Loader", category: "UI Elements", thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=80&h=80&fit=crop", tags: ["ui", "animation"] },
  { id: "wave-3d", name: "Wave", category: "Abstract", thumbnail: "https://images.unsplash.com/photo-1614729375290-b5e05cf26154?w=80&h=80&fit=crop", tags: ["abstract", "fluid"] },
  { id: "grid-3d", name: "3D Grid", category: "Abstract", thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=80&h=80&fit=crop", tags: ["abstract", "pattern"] },
  { id: "spiral-3d", name: "Spiral", category: "Abstract", thumbnail: "https://images.unsplash.com/photo-1600959907703-571c428f0eba?w=80&h=80&fit=crop", tags: ["abstract", "motion"] },
];

export const CANVAS_PRESETS = [
  { name: "1280 × 720 (HD)", width: 1280, height: 720 },
  { name: "1920 × 1080 (Full HD)", width: 1920, height: 1080 },
  { name: "800 × 600 (Web Banner)", width: 800, height: 600 },
  { name: "1200 × 628 (Social OG)", width: 1200, height: 628 },
  { name: "1080 × 1080 (Square)", width: 1080, height: 1080 },
  { name: "1080 × 1920 (Story)", width: 1080, height: 1920 },
  { name: "400 × 400 (Avatar)", width: 400, height: 400 },
  { name: "728 × 90 (Leaderboard)", width: 728, height: 90 },
  { name: "300 × 250 (Rectangle)", width: 300, height: 250 },
];

export const BACKGROUND_PRESETS = [
  { name: "Dark Navy", value: "#0d0d1a" },
  { name: "Pure Black", value: "#000000" },
  { name: "Pure White", value: "#ffffff" },
  { name: "Studio Gray", value: "#1a1a2e" },
  { name: "Deep Space", value: "linear-gradient(135deg, #0a0a1a 0%, #1a0a2e 100%)" },
  { name: "Ocean Depth", value: "linear-gradient(135deg, #0a1a2e 0%, #0a2e2e 100%)" },
  { name: "Neon Sunset", value: "linear-gradient(135deg, #1a0a2e 0%, #2e0a1a 50%, #1a0a0a 100%)" },
  { name: "Cyber Grid", value: "#030712" },
  { name: "Midnight Blue", value: "#0f172a" },
  { name: "Forest Night", value: "#0a1a0a" },
  { name: "Transparent", value: "transparent" },
];

export const BLEND_MODES = [
  "normal", "multiply", "screen", "overlay", "darken", "lighten",
  "color-dodge", "color-burn", "hard-light", "soft-light",
  "difference", "exclusion", "hue", "saturation", "color", "luminosity",
];

export const FONT_FAMILIES = [
  "Inter, sans-serif",
  "Space Grotesk, sans-serif",
  "Georgia, serif",
  "Times New Roman, serif",
  "Courier New, monospace",
  "Arial, sans-serif",
  "Helvetica Neue, sans-serif",
  "Trebuchet MS, sans-serif",
  "Verdana, sans-serif",
  "Impact, sans-serif",
];

export const WEB_ELEMENTS = [
  { id: "badge", name: "Badge", category: "UI", content: '<span style="background:#00d4ff;color:#000;padding:4px 12px;border-radius:999px;font-family:Inter;font-size:12px;font-weight:600">NEW</span>' },
  { id: "button-primary", name: "Primary Button", category: "UI", content: '<button style="background:#00d4ff;color:#000;padding:10px 24px;border:none;border-radius:8px;font-family:Inter;font-size:14px;font-weight:600;cursor:pointer">Get Started →</button>' },
  { id: "button-outline", name: "Outline Button", category: "UI", content: '<button style="background:transparent;color:#00d4ff;padding:10px 24px;border:1.5px solid #00d4ff;border-radius:8px;font-family:Inter;font-size:14px;font-weight:600;cursor:pointer">Learn More</button>' },
  { id: "card", name: "Glass Card", category: "Cards", content: '<div style="background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:16px;padding:24px;backdrop-filter:blur(16px)"><h3 style="color:#fff;font-family:Inter;margin:0 0 8px;font-size:18px">Card Title</h3><p style="color:#9ca3af;font-family:Inter;font-size:14px;margin:0">Card description text goes here</p></div>' },
  { id: "pill-tag", name: "Pill Tag", category: "UI", content: '<span style="background:rgba(0,212,255,0.1);color:#00d4ff;padding:4px 12px;border-radius:999px;font-family:Inter;font-size:12px;border:1px solid rgba(0,212,255,0.3)">Design</span>' },
  { id: "progress-bar", name: "Progress Bar", category: "UI", content: '<div style="width:200px"><div style="background:rgba(255,255,255,0.1);border-radius:999px;height:8px"><div style="background:linear-gradient(90deg,#00d4ff,#7c3aed);width:72%;height:100%;border-radius:999px"></div></div><div style="display:flex;justify-content:space-between;margin-top:4px"><span style="color:#9ca3af;font-family:Inter;font-size:11px">Progress</span><span style="color:#00d4ff;font-family:Inter;font-size:11px;font-weight:600">72%</span></div></div>' },
  { id: "stat-card", name: "Stat Card", category: "Cards", content: '<div style="background:rgba(0,212,255,0.05);border:1px solid rgba(0,212,255,0.2);border-radius:12px;padding:16px;text-align:center"><div style="color:#00d4ff;font-family:Inter;font-size:32px;font-weight:700;margin-bottom:4px">12.4K</div><div style="color:#9ca3af;font-family:Inter;font-size:12px">Monthly Users</div></div>' },
  { id: "avatar", name: "Avatar", category: "UI", content: '<div style="width:48px;height:48px;border-radius:50%;background:linear-gradient(135deg,#00d4ff,#7c3aed);display:flex;align-items:center;justify-content:center;color:#fff;font-family:Inter;font-size:18px;font-weight:600">A</div>' },
  { id: "divider", name: "Gradient Divider", category: "UI", content: '<div style="height:2px;background:linear-gradient(90deg,transparent,#00d4ff,#7c3aed,transparent);width:100%"></div>' },
  { id: "code-block", name: "Code Block", category: "Dev", content: '<pre style="background:#0a0a14;border:1px solid #1e1e3a;border-radius:8px;padding:16px;font-family:Courier New;font-size:13px;color:#e8eaf2;margin:0"><code><span style="color:#00d4ff">const</span> <span style="color:#e8eaf2">result</span> = <span style="color:#10b981">animate</span>(<span style="color:#f59e0b">"fadeIn"</span>);</code></pre>' },
];
